### ISSUE TITLE
Make HDIUTIL_PATH existence check only on any first call?

### ISSUE THREAD

**Issue by myselfhimself** [0xbf00/dmglib#1]
Hello,

Thank you for releasing out this pretty little library :)

if anyone does `import dmglib` on any OS that is not MacOSX, chances are that dmglib's module-top HDI_UTIL existence check will trigger and add noise into logs/stderr for nothing: https://github.com/0xbf00/dmglib/blob/master/src/dmglib.py#L18 
This is really a super picky remark, but for example for [this blender-addon-tester issue](https://github.com/douglaskastle/blender-addon-tester/issues/2), we share a single set of python requirements list for all windows, linux and macos platforms, expecting each of pip-installed modules be bug us on platform-related errors if we run any first function call from them.

What about moving that very existence check into a DiskImage constructor or some unavoidable call within dmglib?

**Comment by 0xbf00** [comment]
Hey! Nice to hear someone is using this little project. Sorry for taking so long to get back to you.

There are a number of standalone functions apart from the `DiskImage` class, so to implement your suggestion correctly would mean adding lots of existence checks. I'd rather keep the changes small.

Would it be helpful to you if `dmglib` threw an `ImportError` on unsupported platforms, which you could then simply handle and ignore? This would also not the ideal solution, because it would require changes on your part (and on the part of whoever else might use this library)

**Comment by myselfhimself** [comment]
Hello,
Thanks for replying :)
OSError could be the proper error: https://docs.python.org/3/library/exceptions.html#OSError
Making changes on our side is OK. Indeed I cannot be in the shoes of the other library's users.

**Comment by myselfhimself** [comment]
Or... EnvironmentError
anyways ImportError was OK too

**Comment by 0xbf00** [comment]
I've just published a new version on PyPI that follows your initial suggestion. `dmglib` now throws an exception (`FileNotFoundError`) when any function is used on a non-macOS system. As far as I can tell, no changes on your end should be necessary. Closing here, if you notice any problems, please let me know!
